CREATE DATABASE IF NOT EXISTS shopping_mall;
USE shopping_mall;

CREATE TABLE IF NOT EXISTS USER(
  USER_ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(255) NOT NULL,
  USER_BALANCE INT(11) NOT NULL,
  PRIMARY KEY(USER_ID)
);

INSERT INTO USER VALUES(0, 'test', 100000);

CREATE TABLE IF NOT EXISTS ITEM(
  ITEM_ID INT(11) NOT NULL AUTO_INCREMENT,
  ITEM_NAME VARCHAR(255) NOT NULL,
  ITEM_PRICE INT NOT NULL,
  PRIMARY KEY(ITEM_ID)
);

INSERT INTO ITEM VALUES(1, 'KEYBOARD', 10000);
INSERT INTO ITEM VALUES(2, 'MONITOR', 30000);
INSERT INTO ITEM VALUES(3, 'TABLE', 50000);
INSERT INTO ITEM VALUES(4, 'CHAIR', 20000);
INSERT INTO ITEM VALUES(5, 'TV', 50000);


CREATE TABLE IF NOT EXISTS PURCHASE(
  PURCHASE_ID INT(11) NOT NULL AUTO_INCREMENT,
  ITEM_ID INT NOT NULL,
  ITEM_COUNT INT NOT NULL,
  PRIMARY KEY(PURCHASE_ID),
  FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

